package src.Choices.Classes;

import src.Choice;
import src.Option;
import src.Question;

import java.util.ArrayList;

public class PldnSub extends Choice {
    public PldnSub(){
        super();
    }
    public ArrayList<Option> run(){
        ArrayList<Option> list = new ArrayList<Option>();
        ArrayList<Option> pick = new ArrayList<Option>();
        pick.add(new Option("Oath of the Ancients (Paladin)"));
        pick.add(new Option("Oath of Conquest (Paladin)"));
        pick.add(new Option("Oath of the Crown (Paladin)"));
        pick.add(new Option("Oath of Devotion (Paladin)"));
        pick.add(new Option("Oath of Glory (Paladin)"));
        pick.add(new Option("Oath of Redemption (Paladin)"));
        pick.add(new Option("Oath of Vengeance (Paladin)"));
        pick.add(new Option("Oath of the Watchers (Paladin)"));
        pick.add(new Option("Oathbreaker (Paladin)"));
        pick.add(new Option("Oath of the Open Sea (Paladin)", false, true));


        pick.add(new Option("Arch Paladin ('dandwiki')(Paladin)", true));
        pick.add(new Option("Envoy of the Dead ('dandwiki')(Paladin)", true));
        pick.add(new Option("Fallen Deity ('dandwiki')(Paladin)", true));
        pick.add(new Option("Immortal Guardians ('dandwiki')(Paladin)", true));
        pick.add(new Option("Knight Templar Oath ('dandwiki')(Paladin)", true));
        pick.add(new Option("Oath of Aid ('dandwiki')(Paladin)", true));
        pick.add(new Option("Oath of Akatosh ('dandwiki')(Paladin)", true));
        pick.add(new Option("Oath of Apocalypse ('dandwiki')(Paladin)", true));
        pick.add(new Option("Oath of Astora ('dandwiki')(Paladin)", true));
        pick.add(new Option("Oath of Balance ('dandwiki')(Paladin)", true));
        pick.add(new Option("Oath of Brawn ('dandwiki')(Paladin)", true));
        pick.add(new Option("Oath of Celibacy ('dandwiki')(Paladin)", true));
        pick.add(new Option("Oath of Chivalry ('dandwiki')(Paladin)", true));
        pick.add(new Option("Oath of Commerce ('dandwiki')(Paladin)", true));
        pick.add(new Option("Oath of Courage ('dandwiki')(Paladin)", true));
        pick.add(new Option("Oath of Covertness ('dandwiki')(Paladin)", true));
        pick.add(new Option("Oath of Death ('dandwiki')(Paladin)", true));
        pick.add(new Option("Oath of Devotion, Variant ('dandwiki')(Paladin)", true));
        pick.add(new Option("Oath of Domination ('dandwiki')(Paladin)", true));
        pick.add(new Option("Oath of Earth ('dandwiki')(Paladin)", true));
        pick.add(new Option("Oath of Eschatology ('dandwiki')(Paladin)", true));
        pick.add(new Option("Oath of Execution ('dandwiki')(Paladin)", true));
        pick.add(new Option("Oath of Forbidden Knowledge ('dandwiki')(Paladin)", true));
        pick.add(new Option("Oath of Furor ('dandwiki')(Paladin)", true));
        pick.add(new Option("Oath of Hellfire ('dandwiki')(Paladin)", true));
        pick.add(new Option("Oath of Hospitality ('dandwiki')(Paladin)", true));
        pick.add(new Option("Oath of Immaculacy ('dandwiki')(Paladin)", true));
        pick.add(new Option("Oath of Improvement ('dandwiki')(Paladin)", true));
        pick.add(new Option("Oath of Infection ('dandwiki')(Paladin)", true));
        pick.add(new Option("Oath of Judgement ('dandwiki')(Paladin)", true));
        pick.add(new Option("Oath of Judgement, Variant ('dandwiki')(Paladin)", true));
        pick.add(new Option("Oath of Knowledge ('dandwiki')(Paladin)", true));
        pick.add(new Option("Oath of Knugen ('dandwiki')(Paladin)", true));
        pick.add(new Option("Oath of Liberation ('dandwiki')(Paladin)", true));
        pick.add(new Option("Oath of Luna ('dandwiki')(Paladin)", true));
        pick.add(new Option("Oath of Mercy ('dandwiki')(Paladin)", true));
        pick.add(new Option("Oath of Mystra ('dandwiki')(Paladin)", true));
        pick.add(new Option("Oath of Peace ('dandwiki')(Paladin)", true));
        pick.add(new Option("Oath of Perfection ('dandwiki')(Paladin)", true));
        pick.add(new Option("Oath of Piracy ('dandwiki')(Paladin)", true));
        pick.add(new Option("Oath of Plague ('dandwiki')(Paladin)", true));
        pick.add(new Option("Oath of Presence ('dandwiki')(Paladin)", true));
        pick.add(new Option("Oath of Protection ('dandwiki')(Paladin)", true));
        pick.add(new Option("Oath of Protection, Variant ('dandwiki')(Paladin)", true));
        pick.add(new Option("Oath of Pugnator ('dandwiki')(Paladin)", true));
        pick.add(new Option("Oath of Ruin ('dandwiki')(Paladin)", true));
        pick.add(new Option("Oath of Sacrifice ('dandwiki')(Paladin)", true));
        pick.add(new Option("Oath of Shielding ('dandwiki')(Paladin)", true));
        pick.add(new Option("Oath of Silence ('dandwiki')(Paladin)", true));
        pick.add(new Option("Oath of Song ('dandwiki')(Paladin)", true));
        pick.add(new Option("Oath of Storm's Legion ('dandwiki')(Paladin)", true));
        pick.add(new Option("Oath of Superiority ('dandwiki')(Paladin)", true));
        pick.add(new Option("Oath of Supremacy ('dandwiki')(Paladin)", true));
        pick.add(new Option("Oath of the Ancient Blades ('dandwiki')(Paladin)", true));
        pick.add(new Option("Oath of the Ancients, Variant ('dandwiki')(Paladin)", true));
        pick.add(new Option("Oath of the Antimage ('dandwiki')(Paladin)", true));
        pick.add(new Option("Oath of the Antimage, Variant ('dandwiki')(Paladin)", true));
        pick.add(new Option("Oath of the Beast ('dandwiki')(Paladin)", true));
        pick.add(new Option("Oath of the Berserker ('dandwiki')(Paladin)", true));
        pick.add(new Option("Oath of the Betrayed ('dandwiki')(Paladin)", true));
        pick.add(new Option("Oath of the Black Bottle ('dandwiki')(Paladin)", true));
        pick.add(new Option("Oath of the Blood Moon ('dandwiki')(Paladin)", true));
        pick.add(new Option("Oath of the Chalice ('dandwiki')(Paladin)", true));
        pick.add(new Option("Oath of the Chosen ('dandwiki')(Paladin)", true));
        pick.add(new Option("Oath of the Corrupted ('dandwiki')(Paladin)", true));
        pick.add(new Option("Oath of the Crimson Legionnaire ('dandwiki')(Paladin)", true));
        pick.add(new Option("Oath of the Crown, 2nd Variant ('dandwiki')(Paladin)", true));
        pick.add(new Option("Oath of the Crown, Variant ('dandwiki')(Paladin)", true));
        pick.add(new Option("Oath of the Crusader ('dandwiki')(Paladin)", true));
        pick.add(new Option("Oath of the Cycle ('dandwiki')(Paladin)", true));
        pick.add(new Option("Oath of the Dagger ('dandwiki')(Paladin)", true));
        pick.add(new Option("Oath of the Dawn Phoenix ('dandwiki')(Paladin)", true));
        pick.add(new Option("Oath of the Death Knight ('dandwiki')(Paladin)", true));
        pick.add(new Option("Oath of the Decaying ('dandwiki')(Paladin)", true));
        pick.add(new Option("Oath of the Deep ('dandwiki')(Paladin)", true));
        pick.add(new Option("Oath of the Defender ('dandwiki')(Paladin)", true));
        pick.add(new Option("Oath of the Despot ('dandwiki')(Paladin)", true));
        pick.add(new Option("Oath of the Dragon ('dandwiki')(Paladin)", true));
        pick.add(new Option("Oath of the Dragon Gods ('dandwiki')(Paladin)", true));
        pick.add(new Option("Oath of the Dragon Gods, Variant ('dandwiki')(Paladin)", true));
        pick.add(new Option("Oath of the Dragon Lineage ('dandwiki')(Paladin)", true));
        pick.add(new Option("Oath of the Dragon Lord ('dandwiki')(Paladin)", true));
        pick.add(new Option("Oath of the Dragons ('dandwiki')(Paladin)", true));
        pick.add(new Option("Oath of the Dusk Phoenix ('dandwiki')(Paladin)", true));
        pick.add(new Option("Oath of the Elements ('dandwiki')(Paladin)", true));
        pick.add(new Option("Oath of the Elements, Variant ('dandwiki')(Paladin)", true));
        pick.add(new Option("Oath of the Eternal Flame ('dandwiki')(Paladin)", true));
        pick.add(new Option("Oath of the Exterminator ('dandwiki')(Paladin)", true));
        pick.add(new Option("Oath of the Fae ('dandwiki')(Paladin)", true));
        pick.add(new Option("Oath of the Fae, Variant ('dandwiki')(Paladin)", true));
        pick.add(new Option("Oath of the Fallen Knight ('dandwiki')(Paladin)", true));
        pick.add(new Option("Oath of the Farseer ('dandwiki')(Paladin)", true));
        pick.add(new Option("Oath of the Forgotten Powers ('dandwiki')(Paladin)", true));
        pick.add(new Option("Oath of the Fury ('dandwiki')(Paladin)", true));
        pick.add(new Option("Oath of the Gargoyle ('dandwiki')(Paladin)", true));
        pick.add(new Option("Oath of the Grave Digger ('dandwiki')(Paladin)", true));
        pick.add(new Option("Oath of the Guardian ('dandwiki')(Paladin)", true));
        pick.add(new Option("Oath of the Guardian, Variant ('dandwiki')(Paladin)", true));
        pick.add(new Option("Oath of the Gun ('dandwiki')(Paladin)", true));
        pick.add(new Option("Oath of the Half-Moon ('dandwiki')(Paladin)", true));
        pick.add(new Option("Oath of the Hand ('dandwiki')(Paladin)", true));
        pick.add(new Option("Oath of the Harvest ('dandwiki')(Paladin)", true));
        pick.add(new Option("Oath of the Hero ('dandwiki')(Paladin)", true));
        pick.add(new Option("Oath of the Holy Gun ('dandwiki')(Paladin)", true));
        pick.add(new Option("Oath of the Horseman ('dandwiki')(Paladin)", true));
        pick.add(new Option("Oath of the Indomitable ('dandwiki')(Paladin)", true));
        pick.add(new Option("Oath of the Inquisition ('dandwiki')(Paladin)", true));
        pick.add(new Option("Oath of the Inquisitor ('dandwiki')(Paladin)", true));
        pick.add(new Option("Oath of the Iron Fist ('dandwiki')(Paladin)", true));
        pick.add(new Option("Oath of the Jedi/Sith ('dandwiki')(Paladin)", true));
        pick.add(new Option("Oath of the Jungle ('dandwiki')(Paladin)", true));
        pick.add(new Option("Oath of the Justiciar ('dandwiki')(Paladin)", true));
        pick.add(new Option("Oath of the Lanternbearer ('dandwiki')(Paladin)", true));
        pick.add(new Option("Oath of the Lawman ('dandwiki')(Paladin)", true));
        pick.add(new Option("Oath of the Legion ('dandwiki')(Paladin)", true));
        pick.add(new Option("Oath of the Leper ('dandwiki')(Paladin)", true));
        pick.add(new Option("Oath of the Lich-Servant ('dandwiki')(Paladin)", true));
        pick.add(new Option("Oath of the Life Protector ('dandwiki')(Paladin)", true));
        pick.add(new Option("Oath of the Light ('dandwiki')(Paladin)", true));
        pick.add(new Option("Oath of the Mage Hunter ('dandwiki')(Paladin)", true));
        pick.add(new Option("Oath of the Mariner ('dandwiki')(Paladin)", true));
        pick.add(new Option("Oath of the Mask ('dandwiki')(Paladin)", true));
        pick.add(new Option("Oath of the Moon ('dandwiki')(Paladin)", true));
        pick.add(new Option("Oath of the Mother ('dandwiki')(Paladin)", true));
        pick.add(new Option("Oath of the Night ('dandwiki')(Paladin)", true));
        pick.add(new Option("Oath of the Nomad ('dandwiki')(Paladin)", true));
        pick.add(new Option("Oath of the Old Ones ('dandwiki')(Paladin)", true));
        pick.add(new Option("Oath of the Pale Knight ('dandwiki')(Paladin)", true));
        pick.add(new Option("Oath of the Purge ('dandwiki')(Paladin)", true));
        pick.add(new Option("Oath of the Rainbow ('dandwiki')(Paladin)", true));
        pick.add(new Option("Oath of the Reaper ('dandwiki')(Paladin)", true));
        pick.add(new Option("Oath of the Rock ('dandwiki')(Paladin)", true));
        pick.add(new Option("Oath of the Samurai ('dandwiki')(Paladin)", true));
        pick.add(new Option("Oath of the Seeker ('dandwiki')(Paladin)", true));
        pick.add(new Option("Oath of the Sentinel ('dandwiki')(Paladin)", true));
        pick.add(new Option("Oath of the Shield ('dandwiki')(Paladin)", true));
        pick.add(new Option("Oath of the Silver Hand ('dandwiki')(Paladin)", true));
        pick.add(new Option("Oath of the Silver Hand, Variant ('dandwiki')(Paladin)", true));
        pick.add(new Option("Oath of the Silver Shield ('dandwiki')(Paladin)", true));
        pick.add(new Option("Oath of the Sin of Pride ('dandwiki')(Paladin)", true));
        pick.add(new Option("Oath of the Skykeeper ('dandwiki')(Paladin)", true));
        pick.add(new Option("Oath of the Storm ('dandwiki')(Paladin)", true));
        pick.add(new Option("Oath of the Templar ('dandwiki')(Paladin)", true));
        pick.add(new Option("Oath of the Temple ('dandwiki')(Paladin)", true));
        pick.add(new Option("Oath of the Torch ('dandwiki')(Paladin)", true));
        pick.add(new Option("Oath of the Torch, Variant ('dandwiki')(Paladin)", true));
        pick.add(new Option("Oath of the Undead Destroyer ('dandwiki')(Paladin)", true));
        pick.add(new Option("Oath of the Undeath ('dandwiki')(Paladin)", true));
        pick.add(new Option("Oath of the Valkyrie ('dandwiki')(Paladin)", true));
        pick.add(new Option("Oath of the Valorous ('dandwiki')(Paladin)", true));
        pick.add(new Option("Oath of the Warlord ('dandwiki')(Paladin)", true));
        pick.add(new Option("Oath of the Watchers, Variant ('dandwiki')(Paladin)", true));
        pick.add(new Option("Oath of the Witchadin ('dandwiki')(Paladin)", true));
        pick.add(new Option("Oath of Time ('dandwiki')(Paladin)", true));
        pick.add(new Option("Oath of Vigilance ('dandwiki')(Paladin)", true));
        pick.add(new Option("Oath of Virtue ('dandwiki')(Paladin)", true));
        pick.add(new Option("Oath of Volition ('dandwiki')(Paladin)", true));
        pick.add(new Option("Oath of War ('dandwiki')(Paladin)", true));
        pick.add(new Option("Oath of Wild Magic ('dandwiki')(Paladin)", true));
        pick.add(new Option("Oathbreaker, Variant ('dandwiki')(Paladin)", true));
        pick.add(new Option("Pseudo Cleric ('dandwiki')(Paladin)", true));
        pick.add(new Option("The First Circle: Fiend Hunters ('dandwiki')(Paladin)", true));
        pick.add(new Option("The Holy Gun ('dandwiki')(Paladin)", true));
        pick.add(new Option("The Second Circle: Undead Destroyers ('dandwiki')(Paladin)", true));
        pick.add(new Option("The Third Circle: Eldritch Slayers ('dandwiki')(Paladin)", true));
        pick.add(new Option("Ushtabi Guardian ('dandwiki')(Paladin)", true));
        Option a = Question.ask(pick, "Choose your Sacred Oath");
        list.add(a);
        pick = new ArrayList<Option>();
        pick.add(new Option("Blessed Warrior (Fighting Style)"));
        pick.add(new Option("Blind Fighting (Fighting Style)"));
        pick.add(new Option("Defence (Fighting Style)"));
        pick.add(new Option("Dueling (Fighting Style)"));
        pick.add(new Option("Great Weapon Fighting (Fighting Style)"));
        pick.add(new Option("Interception (Fighting Style)"));
        pick.add(new Option("Protection (Fighting Style)"));
        pick.add(new Option("Close Quarters Shooter (Fighting Style)", true, false));
        pick.add(new Option("Mariner (Fighting Style)", true, false));
        pick.add(new Option("Thrown Weapon Fighting (Fighting Style)", true, false));
        pick.add(new Option("Tunnel Fighter (Fighting Style)", true, false));
        pick.add(new Option("Unarmed Fighting (Fighting Style)", true, false));

        a = Question.ask(pick, "Choose your Paladin Fighting Style");
        list.add(a);


        return list;
    }
}

