package src.Choices.Classes;

import src.Choice;
import src.Option;
import src.Options.Subchoice;
import src.Question;

import java.util.ArrayList;
import java.util.Arrays;

public class ScrSub extends Choice {
    public ScrSub(){
        super();
    }
    public ArrayList<Option> run(){
        ArrayList<Option> list = new ArrayList<Option>();
        ArrayList<Option> pick = new ArrayList<Option>();
        pick.add(new Option("Aberrant Mind (Sorcerer)"));
        pick.add(new Option("Clockwork Soul (Sorcerer)"));
        pick.add(new Option("Draconic Bloodline (Sorcerer)"));
        pick.add(new Subchoice("Divine Soul (Sorcerer)", new ArrayList<>(Arrays.asList(new ArrayList<>(Arrays.asList(
                new Option ("Good (Affinity)"),
                new Option ("Evil (Affinity)"),
                new Option ("Chaotic (Affinity)"),
                new Option ("Lawful (Affinity)"),
                new Option ("Neutrality (Affinity)")))))));
        pick.add(new Option("Lunar Sorcery (Sorcerer)"));
        pick.add(new Option("Shadow Magic (Sorcerer)"));
        pick.add(new Option("Storm Sorcery (Sorcerer)"));
        pick.add(new Option("Wild Magic (Sorcerer)"));
        pick.add(new Option("Pyromancy (Sorcerer)", true, false));
        pick.add(new Option("Runechild ('Tal'Dorei Campaign Setting Reborn') (Sorcerer)", false, true));
        pick.add(new Option("Aberrant Bloodline ('dandwiki')(Sorcerer)", true));
        pick.add(new Option("Aberrant Bloodline, Variant ('dandwiki')(Sorcerer)", true));
        pick.add(new Option("Arcane Fist ('dandwiki')(Sorcerer)", true));
        pick.add(new Option("Arcane Origin ('dandwiki')(Sorcerer)", true));
        pick.add(new Option("Arcane Origin, Variant ('dandwiki')(Sorcerer)", true));
        pick.add(new Option("Arcane Scientist ('dandwiki')(Sorcerer)", true));
        pick.add(new Option("Arcane Scientist, Variant ('dandwiki')(Sorcerer)", true));
        pick.add(new Option("Arcanist: Scholar ('dandwiki')(Sorcerer)", true));
        pick.add(new Option("Arcanist: Summoner ('dandwiki')(Sorcerer)", true));
        pick.add(new Option("Arcanist: Titansmith ('dandwiki')(Sorcerer)", true));
        pick.add(new Option("Archangel's Blood ('dandwiki')(Sorcerer)", true));
        pick.add(new Option("Arithmetic Soul ('dandwiki')(Sorcerer)", true));
        pick.add(new Option("Asgardian Sorcery ('dandwiki')(Sorcerer)", true));
        pick.add(new Option("Astral Bloodline ('dandwiki')(Sorcerer)", true));
        pick.add(new Option("Astral Sorcery ('dandwiki')(Sorcerer)", true));
        pick.add(new Option("Astral Wanderer ('dandwiki')(Sorcerer)", true));
        pick.add(new Option("Astralborn Bloodline ('dandwiki')(Sorcerer)", true));
        pick.add(new Option("Asylum Origin ('dandwiki')(Sorcerer)", true));
        pick.add(new Option("Atlira Fiend Blood Sorcerer ('dandwiki')(Sorcerer)", true));
        pick.add(new Option("Banshee Soul ('dandwiki')(Sorcerer)", true));
        pick.add(new Option("Battle Sorcerer ('dandwiki')(Sorcerer)", true));
        pick.add(new Option("Battle Sorcerer, Variant ('dandwiki')(Sorcerer)", true));
        pick.add(new Option("Battle Sorcery ('dandwiki')(Sorcerer)", true));
        pick.add(new Option("Battle Soul ('dandwiki')(Sorcerer)", true));
        pick.add(new Option("Beholder Bloodline ('dandwiki')(Sorcerer)", true));
        pick.add(new Option("Believer ('dandwiki')(Sorcerer)", true));
        pick.add(new Option("Blade Born ('dandwiki')(Sorcerer)", true));
        pick.add(new Option("Bladecaller ('dandwiki')(Sorcerer)", true));
        pick.add(new Option("Blessing of the Gods Sorcery ('dandwiki')(Sorcerer)", true));
        pick.add(new Option("Blood Mage ('dandwiki')(Sorcerer)", true));
        pick.add(new Option("Blood Sorcerer ('dandwiki')(Sorcerer)", true));
        pick.add(new Option("Blood Sorcery ('dandwiki')(Sorcerer)", true));
        pick.add(new Option("Blood Sorcery, Variant ('dandwiki')(Sorcerer)", true));
        pick.add(new Option("Bloodbeast Origin ('dandwiki')(Sorcerer)", true));
        pick.add(new Option("Bloodline of Everfliers ('dandwiki')(Sorcerer)", true));
        pick.add(new Option("Born and Bred ('dandwiki')(Sorcerer)", true));
        pick.add(new Option("Bound Bloodline ('dandwiki')(Sorcerer)", true));
        pick.add(new Option("Burning Soul Origin ('dandwiki')(Sorcerer)", true));
        pick.add(new Option("Caledorian Dragon Mage Bloodline ('dandwiki')(Sorcerer)", true));
        pick.add(new Option("Card Mage ('dandwiki')(Sorcerer)", true));
        pick.add(new Option("Catastrophic Origin ('dandwiki')(Sorcerer)", true));
        pick.add(new Option("Chaos Pyromancy ('dandwiki')(Sorcerer)", true));
        pick.add(new Option("Chronos Origin ('dandwiki')(Sorcerer)", true));
        pick.add(new Option("Chronos Soul ('dandwiki')(Sorcerer)", true));
        pick.add(new Option("Cold Heart ('dandwiki')(Sorcerer)", true));
        pick.add(new Option("Combat Magic ('dandwiki')(Sorcerer)", true));
        pick.add(new Option("Concentration Everfliers ('dandwiki')(Sorcerer)", true));
        pick.add(new Option("Concrete Conduit ('dandwiki')(Sorcerer)", true));
        pick.add(new Option("Coral Magic ('dandwiki')(Sorcerer)", true));
        pick.add(new Option("Corrupted Lineage ('dandwiki')(Sorcerer)", true));
        pick.add(new Option("Cryogenist ('dandwiki')(Sorcerer)", true));
        pick.add(new Option("Crystal Mother ('dandwiki')(Sorcerer)", true));
        pick.add(new Option("Cursed Soul ('dandwiki')(Sorcerer)", true));
        pick.add(new Option("Deathtouched ('dandwiki')(Sorcerer)", true));
        pick.add(new Option("Demonic Divinity Origin ('dandwiki')(Sorcerer)", true));
        pick.add(new Option("Destined Bloodline ('dandwiki')(Sorcerer)", true));
        pick.add(new Option("Devil Bloodline ('dandwiki')(Sorcerer)", true));
        pick.add(new Option("Divine Bloodline ('dandwiki')(Sorcerer)", true));
        pick.add(new Option("Divine Bloodline, Variant ('dandwiki')(Sorcerer)", true));
        pick.add(new Option("Divine Soul, 2nd Variant ('dandwiki')(Sorcerer)", true));
        pick.add(new Option("Draconic Bloodline, Variant ('dandwiki')(Sorcerer)", true));
        pick.add(new Option("Draconic Sorcerer ('dandwiki')(Sorcerer)", true));
        pick.add(new Option("Draconic Warrior, Variant ('dandwiki')(Sorcerer)", true));
        pick.add(new Option("Dragon Blood Origin ('dandwiki')(Sorcerer)", true));
        pick.add(new Option("Dragon's Blessing ('dandwiki')(Sorcerer)", true));
        pick.add(new Option("Dread ('dandwiki')(Sorcerer)", true));
        pick.add(new Option("Earthborne Bloodline ('dandwiki')(Sorcerer)", true));
        pick.add(new Option("Eighth Hour - Carceri ('dandwiki')(Sorcerer)", true));
        pick.add(new Option("Eldritch Sorcery ('dandwiki')(Sorcerer)", true));
        pick.add(new Option("Elemental Origin ('dandwiki')(Sorcerer)", true));
        pick.add(new Option("Elementalist, Variant ('dandwiki')(Sorcerer)", true));
        pick.add(new Option("Eleventh Hour - The Nine Hells ('dandwiki')(Sorcerer)", true));
        pick.add(new Option("Eloquent Sage ('dandwiki')(Sorcerer)", true));
        pick.add(new Option("Embodiment of Lust ('dandwiki')(Sorcerer)", true));
        pick.add(new Option("Empowerment ('dandwiki')(Sorcerer)", true));
        pick.add(new Option("Empty Wanderer ('dandwiki')(Sorcerer)", true));
        pick.add(new Option("Enchantress Bloodline ('dandwiki')(Sorcerer)", true));
        pick.add(new Option("Ethereal Bloodline ('dandwiki')(Sorcerer)", true));
        pick.add(new Option("Evoker (MC) ('dandwiki')(Sorcerer)", true));
        pick.add(new Option("Fae Bloodline ('dandwiki')(Sorcerer)", true));
        pick.add(new Option("Faintly Accursed ('dandwiki')(Sorcerer)", true));
        pick.add(new Option("Favored Soul Rework ('dandwiki')(Sorcerer)", true));
        pick.add(new Option("Favored Soul, Variant ('dandwiki')(Sorcerer)", true));
        pick.add(new Option("Favoured Soul, 2nd Variant ('dandwiki')(Sorcerer)", true));
        pick.add(new Option("Fey Bloodline ('dandwiki')(Sorcerer)", true));
        pick.add(new Option("Fey Bloodline, Variant ('dandwiki')(Sorcerer)", true));
        pick.add(new Option("Fey-Thane Bloodline ('dandwiki')(Sorcerer)", true));
        pick.add(new Option("Fiend Blood Origin ('dandwiki')(Sorcerer)", true));
        pick.add(new Option("Fiend Bloodline ('dandwiki')(Sorcerer)", true));
        pick.add(new Option("Fiendish Blade Sorcerer ('dandwiki')(Sorcerer)", true));
        pick.add(new Option("Fiendish Bloodline ('dandwiki')(Sorcerer)", true));
        pick.add(new Option("Fifteenth Hour - Mount Celestia ('dandwiki')(Sorcerer)", true));
        pick.add(new Option("Fifth Hour - Limbo ('dandwiki')(Sorcerer)", true));
        pick.add(new Option("Fire Warrior of the Lost ('dandwiki')(Sorcerer)", true));
        pick.add(new Option("Firebending Origin ('dandwiki')(Sorcerer)", true));
        pick.add(new Option("First Hour - Elysium ('dandwiki')(Sorcerer)", true));
        pick.add(new Option("Force Mage ('dandwiki')(Sorcerer)", true));
        pick.add(new Option("Fourteenth Hour - Arcadia ('dandwiki')(Sorcerer)", true));
        pick.add(new Option("Fourth Hour - Ysgard ('dandwiki')(Sorcerer)", true));
        pick.add(new Option("Foxtail Bloodline ('dandwiki')(Sorcerer)", true));
        pick.add(new Option("Foxtail Bloodline, 2nd Variant ('dandwiki')(Sorcerer)", true));
        pick.add(new Option("Fragile Body ('dandwiki')(Sorcerer)", true));
        pick.add(new Option("Frenzied ('dandwiki')(Sorcerer)", true));
        pick.add(new Option("Frost Origin ('dandwiki')(Sorcerer)", true));
        pick.add(new Option("Frost Sorcery ('dandwiki')(Sorcerer)", true));
        pick.add(new Option("Frost-touched Bloodline ('dandwiki')(Sorcerer)", true));
        pick.add(new Option("Genie Origin ('dandwiki')(Sorcerer)", true));
        pick.add(new Option("Glitched Sorcerer ('dandwiki')(Sorcerer)", true));
        pick.add(new Option("Grave Sorcerer ('dandwiki')(Sorcerer)", true));
        pick.add(new Option("Great Old One Bloodline ('dandwiki')(Sorcerer)", true));
        pick.add(new Option("Hag Bloodline ('dandwiki')(Sorcerer)", true));
        pick.add(new Option("Half Cold, Half Fire ('dandwiki')(Sorcerer)", true));
        pick.add(new Option("Half Cold, Half Heat ('dandwiki')(Sorcerer)", true));
        pick.add(new Option("Hellborn Bloodline ('dandwiki')(Sorcerer)", true));
        pick.add(new Option("Hexer Origin ('dandwiki')(Sorcerer)", true));
        pick.add(new Option("Hydric Bloodline ('dandwiki')(Sorcerer)", true));
        pick.add(new Option("Ice Origin ('dandwiki')(Sorcerer)", true));
        pick.add(new Option("Ice Rock ('dandwiki')(Sorcerer)", true));
        pick.add(new Option("Incantatrix ('dandwiki')(Sorcerer)", true));
        pick.add(new Option("Indigo Magic ('dandwiki')(Sorcerer)", true));
        pick.add(new Option("Infernal Birth ('dandwiki')(Sorcerer)", true));
        pick.add(new Option("Inferno ('dandwiki')(Sorcerer)", true));
        pick.add(new Option("Insanity Magic ('dandwiki')(Sorcerer)", true));
        pick.add(new Option("Jedi/Sith Origin ('dandwiki')(Sorcerer)", true));
        pick.add(new Option("Kaleidogen ('dandwiki')(Sorcerer)", true));
        pick.add(new Option("Karmic Soul ('dandwiki')(Sorcerer)", true));
        pick.add(new Option("Ki Soul Origin ('dandwiki')(Sorcerer)", true));
        pick.add(new Option("Kineticist ('dandwiki')(Sorcerer)", true));
        pick.add(new Option("Knight Enchanter ('dandwiki')(Sorcerer)", true));
        pick.add(new Option("Kraken Bloodline ('dandwiki')(Sorcerer)", true));
        pick.add(new Option("Limbo Lineage ('dandwiki')(Sorcerer)", true));
        pick.add(new Option("Lithic Bloodline ('dandwiki')(Sorcerer)", true));
        pick.add(new Option("Lore Savant ('dandwiki')(Sorcerer)", true));
        pick.add(new Option("Love Princess ('dandwiki')(Sorcerer)", true));
        pick.add(new Option("Lucky One ('dandwiki')(Sorcerer)", true));
        pick.add(new Option("Lycan Bloodline ('dandwiki')(Sorcerer)", true));
        pick.add(new Option("Maestro ('dandwiki')(Sorcerer)", true));
        pick.add(new Option("Magic Wrought ('dandwiki')(Sorcerer)", true));
        pick.add(new Option("Magical Girl ('dandwiki')(Sorcerer)", true));
        pick.add(new Option("Magus Bloodline ('dandwiki')(Sorcerer)", true));
        pick.add(new Option("Martial Soul ('dandwiki')(Sorcerer)", true));
        pick.add(new Option("Modron Bloodline ('dandwiki')(Sorcerer)", true));
        pick.add(new Option("Muscle Magic ('dandwiki')(Sorcerer)", true));
        pick.add(new Option("Muscle Magic, Second Variant ('dandwiki')(Sorcerer)", true));
        pick.add(new Option("Muscle Magic, Variant ('dandwiki')(Sorcerer)", true));
        pick.add(new Option("Muscle Sorcerer, Variant ('dandwiki')(Sorcerer)", true));
        pick.add(new Option("Mystic Frost ('dandwiki')(Sorcerer)", true));
        pick.add(new Option("Necromancy Bloodline ('dandwiki')(Sorcerer)", true));
        pick.add(new Option("Neon Conduit ('dandwiki')(Sorcerer)", true));
        pick.add(new Option("Nightmare Origin ('dandwiki')(Sorcerer)", true));
        pick.add(new Option("Ninth Hour - Hades ('dandwiki')(Sorcerer)", true));
        pick.add(new Option("Nothic Bloodline ('dandwiki')(Sorcerer)", true));
        pick.add(new Option("Old Blood ('dandwiki')(Sorcerer)", true));
        pick.add(new Option("Ooze Bloodline ('dandwiki')(Sorcerer)", true));
        pick.add(new Option("Pact of the Demonic Dragon ('dandwiki')(Sorcerer)", true));
        pick.add(new Option("Persona User ('dandwiki')(Sorcerer)", true));
        pick.add(new Option("Phoenix Bloodline ('dandwiki')(Sorcerer)", true));
        pick.add(new Option("Plagueborn Bloodline ('dandwiki')(Sorcerer)", true));
        pick.add(new Option("Planeswalker ('dandwiki')(Sorcerer)", true));
        pick.add(new Option("Primordial Magic ('dandwiki')(Sorcerer)", true));
        pick.add(new Option("Primordial Renewer ('dandwiki')(Sorcerer)", true));
        pick.add(new Option("Profane Soul ('dandwiki')(Sorcerer)", true));
        pick.add(new Option("Psychokinetic ('dandwiki')(Sorcerer)", true));
        pick.add(new Option("Psychotic Blood Sorcerer ('dandwiki')(Sorcerer)", true));
        pick.add(new Option("Puppeteer Sorcerer ('dandwiki')(Sorcerer)", true));
        pick.add(new Option("Puppeteer Sorcerer, Variant ('dandwiki')(Sorcerer)", true));
        pick.add(new Option("Pyral Bloodline ('dandwiki')(Sorcerer)", true));
        pick.add(new Option("Pyromancer, Variant ('dandwiki')(Sorcerer)", true));
        pick.add(new Option("Radiant Soul ('dandwiki')(Sorcerer)", true));
        pick.add(new Option("Rakshasa Bloodline ('dandwiki')(Sorcerer)", true));
        pick.add(new Option("Raw Magic ('dandwiki')(Sorcerer)", true));
        pick.add(new Option("Reincarnated ('dandwiki')(Sorcerer)", true));
        pick.add(new Option("Rift Sorcery ('dandwiki')(Sorcerer)", true));
        pick.add(new Option("Rooted Soul ('dandwiki')(Sorcerer)", true));
        pick.add(new Option("Sandborn Sorcery ('dandwiki')(Sorcerer)", true));
        pick.add(new Option("Sanguine Scion ('dandwiki')(Sorcerer)", true));
        pick.add(new Option("Scion ('dandwiki')(Sorcerer)", true));
        pick.add(new Option("Second Hour - The Beastlands ('dandwiki')(Sorcerer)", true));
        pick.add(new Option("Seventh Hour - The Abyss ('dandwiki')(Sorcerer)", true));
        pick.add(new Option("Shadow Adept ('dandwiki')(Sorcerer)", true));
        pick.add(new Option("Shadow Dragon Bloodline ('dandwiki')(Sorcerer)", true));
        pick.add(new Option("Shadowslinger Origin ('dandwiki')(Sorcerer)", true));
        pick.add(new Option("Shoggoth Bloodline ('dandwiki')(Sorcerer)", true));
        pick.add(new Option("Siren Soul ('dandwiki')(Sorcerer)", true));
        pick.add(new Option("Sixteenth Hour - Bytopia ('dandwiki')(Sorcerer)", true));
        pick.add(new Option("Sixth Hour - Pandemonium ('dandwiki')(Sorcerer)", true));
        pick.add(new Option("Smoke Conduit ('dandwiki')(Sorcerer)", true));
        pick.add(new Option("Smoky Soul ('dandwiki')(Sorcerer)", true));
        pick.add(new Option("Soul Ripper ('dandwiki')(Sorcerer)", true));
        pick.add(new Option("Space Wanderer ('dandwiki')(Sorcerer)", true));
        pick.add(new Option("Spellblade ('dandwiki')(Sorcerer)", true));
        pick.add(new Option("Steelborn ('dandwiki')(Sorcerer)", true));
        pick.add(new Option("Stone sorcery, Remade ('dandwiki')(Sorcerer)", true));
        pick.add(new Option("Storm Bloodline, Variant ('dandwiki')(Sorcerer)", true));
        pick.add(new Option("Storm Bringer ('dandwiki')(Sorcerer)", true));
        pick.add(new Option("Sugar Warrior ('dandwiki')(Sorcerer)", true));
        pick.add(new Option("Sword Sorcery ('dandwiki')(Sorcerer)", true));
        pick.add(new Option("Swordsoul ('dandwiki')(Sorcerer)", true));
        pick.add(new Option("Tarot Mage ('dandwiki')(Sorcerer)", true));
        pick.add(new Option("Tarrasquian Bloodline ('dandwiki')(Sorcerer)", true));
        pick.add(new Option("Tempest Sorcerer ('dandwiki')(Sorcerer)", true));
        pick.add(new Option("Tenth Hour - Gehenna ('dandwiki')(Sorcerer)", true));
        pick.add(new Option("Thalassic Bloodline ('dandwiki')(Sorcerer)", true));
        pick.add(new Option("The Beat ('dandwiki')(Sorcerer)", true));
        pick.add(new Option("The Mad God Maraaq’ ('dandwiki')(Sorcerer)", true));
        pick.add(new Option("The Piper's Soul ('dandwiki')(Sorcerer)", true));
        pick.add(new Option("The Shadow Weave ('dandwiki')(Sorcerer)", true));
        pick.add(new Option("The Shaper ('dandwiki')(Sorcerer)", true));
        pick.add(new Option("Third Hour - Arborea ('dandwiki')(Sorcerer)", true));
        pick.add(new Option("Thirteenth Hour - Mechanus ('dandwiki')(Sorcerer)", true));
        pick.add(new Option("Thought Mage ('dandwiki')(Sorcerer)", true));
        pick.add(new Option("Thought Mage, Variant ('dandwiki')(Sorcerer)", true));
        pick.add(new Option("Tide Shifter ('dandwiki')(Sorcerer)", true));
        pick.add(new Option("Time Sorcery ('dandwiki')(Sorcerer)", true));
        pick.add(new Option("Titan Soul ('dandwiki')(Sorcerer)", true));
        pick.add(new Option("Transformative Magic ('dandwiki')(Sorcerer)", true));
        pick.add(new Option("Trickster Soul ('dandwiki')(Sorcerer)", true));
        pick.add(new Option("True Blood of the Dragon ('dandwiki')(Sorcerer)", true));
        pick.add(new Option("True Hero's Soul ('dandwiki')(Sorcerer)", true));
        pick.add(new Option("True King ('dandwiki')(Sorcerer)", true));
        pick.add(new Option("True Striker ('dandwiki')(Sorcerer)", true));
        pick.add(new Option("Twelfth Hour - Archeron ('dandwiki')(Sorcerer)", true));
        pick.add(new Option("Undead Soul ('dandwiki')(Sorcerer)", true));
        pick.add(new Option("Undeath ('dandwiki')(Sorcerer)", true));
        pick.add(new Option("Unstable Soul ('dandwiki')(Sorcerer)", true));
        pick.add(new Option("Verdant Bloodline ('dandwiki')(Sorcerer)", true));
        pick.add(new Option("Vergeweaver ('dandwiki')(Sorcerer)", true));
        pick.add(new Option("Vessel of the Elements ('dandwiki')(Sorcerer)", true));
        pick.add(new Option("Void Soul ('dandwiki')(Sorcerer)", true));
        pick.add(new Option("Vow to the Word ('dandwiki')(Sorcerer)", true));
        pick.add(new Option("Warrior Bloodline ('dandwiki')(Sorcerer)", true));
        pick.add(new Option("Waterborne ('dandwiki')(Sorcerer)", true));
        pick.add(new Option("Weapon Soul ('dandwiki')(Sorcerer)", true));
        pick.add(new Option("Wild Soul Origin ('dandwiki')(Sorcerer)", true));
        pick.add(new Option("Winter Soul ('dandwiki')(Sorcerer)", true));
        pick.add(new Option("Winter Touched ('dandwiki')(Sorcerer)", true));
        pick.add(new Option("Witchborn ('dandwiki')(Sorcerer)", true));
        Option a = Question.ask(pick, "Choose your Sorcerous Origin");
        list.add(a);
        pick = new ArrayList<Option>();
        pick.add(new Option("Carefull Spell (Metamagic)"));
        pick.add(new Option("Distant Spell (Metamagic)"));
        pick.add(new Option("Empowered Spell (Metamagic)"));
        pick.add(new Option("Extended Spell (Metamagic)"));
        pick.add(new Option("Heightened Spell (Metamagic)"));
        pick.add(new Option("Quickened Spell (Metamagic)"));
        pick.add(new Option("Seeking Spell (Metamagic)"));
        pick.add(new Option("Subtle Spell (Metamagic)"));
        pick.add(new Option("Transmuted Spell (Metamagic)"));
        pick.add(new Option("Twinned Spell (Metamagic)"));
        a = Question.ask(pick, "Choose your Metamagic Option");
        list.add(a);
        pick.remove(a);
        a = Question.ask(pick, "Choose your Second Metamagic Option");
        list.add(a);

        return list;
    }
}

