package src.Choices.Classes;

import src.Choice;
import src.Option;
import src.Options.Subchoice;
import src.Question;

import java.util.ArrayList;
import java.util.Arrays;

public class WlkSub extends Choice {
    public WlkSub(){
        super();
    }
    public ArrayList<Option> run(){
        ArrayList<Option> list = new ArrayList<Option>();
        ArrayList<Option> pick = new ArrayList<Option>();
        pick.add(new Option("Archfey (Warlock)"));
        pick.add(new Option("Celestial (Warlock)"));
        pick.add(new Option("Fathomless (Warlock)"));
        pick.add(new Option("Fiend (Warlock)"));
        pick.add(new Option("Genie (Warlock)"));
        pick.add(new Subchoice("Genie (Warlock)", new ArrayList<>(Arrays.asList(new ArrayList<>(Arrays.asList(
                new Option ("Dao (Genie)"),
                new Option ("Djinni (Genie)"),
                new Option ("Efreeti (Genie)"),
                new Option ("Marid (Genie)")))))));
        pick.add(new Option("Great Old One (Warlock)"));
        pick.add(new Option("Hexblade (Warlock)"));
        pick.add(new Option("Undead (Warlock)"));
        pick.add(new Option("Undying (Warlock)"));
        pick.add(new Option("Kraken ('ThinkDM') (Warlock)", false, true));


        pick.add(new Option("All-Knowing ('dandwiki')(Warlock)", true));
        pick.add(new Option("Archmage Patron ('dandwiki')(Warlock)", true));
        pick.add(new Option("Aspect of Twilight ('dandwiki')(Warlock)", true));
        pick.add(new Option("Astral Walker ('dandwiki')(Warlock)", true));
        pick.add(new Option("Auromancer ('dandwiki')(Warlock)", true));
        pick.add(new Option("Buer ('dandwiki')(Warlock)", true));
        pick.add(new Option("Bugg-Shash ('dandwiki')(Warlock)", true));
        pick.add(new Option("Burning Wind ('dandwiki')(Warlock)", true));
        pick.add(new Option("Celestial, Variant ('dandwiki')(Warlock)", true));
        pick.add(new Option("Citadel of Goodwin ('dandwiki')(Warlock)", true));
        pick.add(new Option("CPU Blue Heart ('dandwiki')(Warlock)", true));
        pick.add(new Option("Cubi Monarch ('dandwiki')(Warlock)", true));
        pick.add(new Option("Dark Angel ('dandwiki')(Warlock)", true));
        pick.add(new Option("Death Note ('dandwiki')(Warlock)", true));
        pick.add(new Option("Demonic Little Grey Cat ('dandwiki')(Warlock)", true));
        pick.add(new Option("Dragon Patron, 2nd Variant ('dandwiki')(Warlock)", true));
        pick.add(new Option("Fire Disciple ('dandwiki')(Warlock)", true));
        pick.add(new Option("Forge Master Patron ('dandwiki')(Warlock)", true));
        pick.add(new Option("Ghost Dragon Patron ('dandwiki')(Warlock)", true));
        pick.add(new Option("Gourmet ('dandwiki')(Warlock)", true));
        pick.add(new Option("Gulthias Tree ('dandwiki')(Warlock)", true));
        pick.add(new Option("Hexgun ('dandwiki')(Warlock)", true));
        pick.add(new Option("Hexgun, Variant ('dandwiki')(Warlock)", true));
        pick.add(new Option("Hunter Patron ('dandwiki')(Warlock)", true));
        pick.add(new Option("Jinx ('dandwiki')(Warlock)", true));
        pick.add(new Option("Judge of the Dead ('dandwiki')(Warlock)", true));
        pick.add(new Option("Juiblex Cultist ('dandwiki')(Warlock)", true));
        pick.add(new Option("Know ('dandwiki')(Warlock)", true));
        pick.add(new Option("Lord of the Unknown ('dandwiki')(Warlock)", true));
        pick.add(new Option("Lord of the Unknown, Variant ('dandwiki')(Warlock)", true));
        pick.add(new Option("Magical Girl ('dandwiki')(Warlock)", true));
        pick.add(new Option("My Ancestors ('dandwiki')(Warlock)", true));
        pick.add(new Option("Night Drifter ('dandwiki')(Warlock)", true));
        pick.add(new Option("Pact of Dozan ('dandwiki')(Warlock)", true));
        pick.add(new Option("Pact of Perfect Pitch ('dandwiki')(Warlock)", true));
        pick.add(new Option("Pact of the Vampire ('dandwiki')(Warlock)", true));
        pick.add(new Option("Poltergeist Patron, Warlock ('dandwiki')(Warlock)", true));
        pick.add(new Option("Poseidon ('dandwiki')(Warlock)", true));
        pick.add(new Option("Pumpkin King ('dandwiki')(Warlock)", true));
        pick.add(new Option("Quantumancer ('dandwiki')(Warlock)", true));
        pick.add(new Option("Reality ('dandwiki')(Warlock)", true));
        pick.add(new Option("Red Ray ('dandwiki')(Warlock)", true));
        pick.add(new Option("Rimuru Tempest Subordinate ('dandwiki')(Warlock)", true));
        pick.add(new Option("Shadow Patron ('dandwiki')(Warlock)", true));
        pick.add(new Option("Slaughterer ('dandwiki')(Warlock)", true));
        pick.add(new Option("Soul Sworn ('dandwiki')(Warlock)", true));
        pick.add(new Option("Soul Warden ('dandwiki')(Warlock)", true));
        pick.add(new Option("Stand ('dandwiki')(Warlock)", true));
        pick.add(new Option("Stone Obelisk ('dandwiki')(Warlock)", true));
        pick.add(new Option("Succubus Queen Patron ('dandwiki')(Warlock)", true));
        pick.add(new Option("Succubus's Toy ('dandwiki')(Warlock)", true));
        pick.add(new Option("Sugar Daddy ('dandwiki')(Warlock)", true));
        pick.add(new Option("Symbiote ('dandwiki')(Warlock)", true));
        pick.add(new Option("Tethered Warlock ('dandwiki')(Warlock)", true));
        pick.add(new Option("The Aberration ('dandwiki')(Warlock)", true));
        pick.add(new Option("The Acidious One ('dandwiki')(Warlock)", true));
        pick.add(new Option("The Aetheric Patron ('dandwiki')(Warlock)", true));
        pick.add(new Option("The Alchemist ('dandwiki')(Warlock)", true));
        pick.add(new Option("The Alien God ('dandwiki')(Warlock)", true));
        pick.add(new Option("The All-Seer ('dandwiki')(Warlock)", true));
        pick.add(new Option("The Ancient Dragon ('dandwiki')(Warlock)", true));
        pick.add(new Option("The Ancient Ones ('dandwiki')(Warlock)", true));
        pick.add(new Option("The Archangel ('dandwiki')(Warlock)", true));
        pick.add(new Option("The Archangel, Variant ('dandwiki')(Warlock)", true));
        pick.add(new Option("The Archfey, Variant ('dandwiki')(Warlock)", true));
        pick.add(new Option("The Archfiend ('dandwiki')(Warlock)", true));
        pick.add(new Option("The Archivists ('dandwiki')(Warlock)", true));
        pick.add(new Option("The Archmage ('dandwiki')(Warlock)", true));
        pick.add(new Option("The Beast ('dandwiki')(Warlock)", true));
        pick.add(new Option("The Beast King ('dandwiki')(Warlock)", true));
        pick.add(new Option("The Beholden ('dandwiki')(Warlock)", true));
        pick.add(new Option("The Beholden, Variant ('dandwiki')(Warlock)", true));
        pick.add(new Option("The Black Flame ('dandwiki')(Warlock)", true));
        pick.add(new Option("The Blood Sponsor ('dandwiki')(Warlock)", true));
        pick.add(new Option("The Bloody Hunt ('dandwiki')(Warlock)", true));
        pick.add(new Option("The Blue Dragon ('dandwiki')(Warlock)", true));
        pick.add(new Option("The Bound God ('dandwiki')(Warlock)", true));
        pick.add(new Option("The Box ('dandwiki')(Warlock)", true));
        pick.add(new Option("The Burning One ('dandwiki')(Warlock)", true));
        pick.add(new Option("The C'tan ('dandwiki')(Warlock)", true));
        pick.add(new Option("The Carar Host ('dandwiki')(Warlock)", true));
        pick.add(new Option("The Cave Being ('dandwiki')(Warlock)", true));
        pick.add(new Option("The Ceaseless Watcher ('dandwiki')(Warlock)", true));
        pick.add(new Option("The Chained God ('dandwiki')(Warlock)", true));
        pick.add(new Option("The Chosen One ('dandwiki')(Warlock)", true));
        pick.add(new Option("The Christmas Spirit Pact ('dandwiki')(Warlock)", true));
        pick.add(new Option("The Cookie Universe ('dandwiki')(Warlock)", true));
        pick.add(new Option("The Corrupted ('dandwiki')(Warlock)", true));
        pick.add(new Option("The Cosmic Patron ('dandwiki')(Warlock)", true));
        pick.add(new Option("The Covenantblade ('dandwiki')(Warlock)", true));
        pick.add(new Option("The Crawling Rot ('dandwiki')(Warlock)", true));
        pick.add(new Option("The Crimson Lord ('dandwiki')(Warlock)", true));
        pick.add(new Option("The Dark Seldarine ('dandwiki')(Warlock)", true));
        pick.add(new Option("The Dead King ('dandwiki')(Warlock)", true));
        pick.add(new Option("The Dealmaker ('dandwiki')(Warlock)", true));
        pick.add(new Option("The Deep Creature ('dandwiki')(Warlock)", true));
        pick.add(new Option("The Deep Curse ('dandwiki')(Warlock)", true));
        pick.add(new Option("The Deep Patron ('dandwiki')(Warlock)", true));
        pick.add(new Option("The Dictator ('dandwiki')(Warlock)", true));
        pick.add(new Option("The Dragon ('dandwiki')(Warlock)", true));
        pick.add(new Option("The Dragon Patron, Variant ('dandwiki')(Warlock)", true));
        pick.add(new Option("The Dragon's Scale ('dandwiki')(Warlock)", true));
        pick.add(new Option("The Dream Dweller ('dandwiki')(Warlock)", true));
        pick.add(new Option("The Dreaming ('dandwiki')(Warlock)", true));
        pick.add(new Option("The Dreamwalker ('dandwiki')(Warlock)", true));
        pick.add(new Option("The Dreamweaver Patron ('dandwiki')(Warlock)", true));
        pick.add(new Option("The Earth Mother ('dandwiki')(Warlock)", true));
        pick.add(new Option("The Earthen King ('dandwiki')(Warlock)", true));
        pick.add(new Option("The Earthmother ('dandwiki')(Warlock)", true));
        pick.add(new Option("The Eater ('dandwiki')(Warlock)", true));
        pick.add(new Option("The Eidolon ('dandwiki')(Warlock)", true));
        pick.add(new Option("The Elder Dragon of Crystal ('dandwiki')(Warlock)", true));
        pick.add(new Option("The Elder Dragon of Death ('dandwiki')(Warlock)", true));
        pick.add(new Option("The Elder Dragon of Fire ('dandwiki')(Warlock)", true));
        pick.add(new Option("The Elder Dragon of Ice ('dandwiki')(Warlock)", true));
        pick.add(new Option("The Elder Dragon of Light ('dandwiki')(Warlock)", true));
        pick.add(new Option("The Elder Dragon of Plants ('dandwiki')(Warlock)", true));
        pick.add(new Option("The Elder Dragon of Water ('dandwiki')(Warlock)", true));
        pick.add(new Option("The Elder Sovereign ('dandwiki')(Warlock)", true));
        pick.add(new Option("The Elder Spirit ('dandwiki')(Warlock)", true));
        pick.add(new Option("The Eldritch Alchemist ('dandwiki')(Warlock)", true));
        pick.add(new Option("The Elemental ('dandwiki')(Warlock)", true));
        pick.add(new Option("The Falling Titan ('dandwiki')(Warlock)", true));
        pick.add(new Option("The Famished ('dandwiki')(Warlock)", true));
        pick.add(new Option("The Feral Sovereign ('dandwiki')(Warlock)", true));
        pick.add(new Option("The Fiend-Blade ('dandwiki')(Warlock)", true));
        pick.add(new Option("The Fire Fiend ('dandwiki')(Warlock)", true));
        pick.add(new Option("The First Dragon ('dandwiki')(Warlock)", true));
        pick.add(new Option("The Flesh ('dandwiki')(Warlock)", true));
        pick.add(new Option("The Force Patron ('dandwiki')(Warlock)", true));
        pick.add(new Option("The Forest Incarnate ('dandwiki')(Warlock)", true));
        pick.add(new Option("The Forever Blind ('dandwiki')(Warlock)", true));
        pick.add(new Option("The Forgotten One ('dandwiki')(Warlock)", true));
        pick.add(new Option("The Formless One ('dandwiki')(Warlock)", true));
        pick.add(new Option("The Four Horsemen ('dandwiki')(Warlock)", true));
        pick.add(new Option("The Furies ('dandwiki')(Warlock)", true));
        pick.add(new Option("The Game King ('dandwiki')(Warlock)", true));
        pick.add(new Option("The Gearmind ('dandwiki')(Warlock)", true));
        pick.add(new Option("The Genie, 2nd Variant ('dandwiki')(Warlock)", true));
        pick.add(new Option("The Genie, Variant ('dandwiki')(Warlock)", true));
        pick.add(new Option("The Glutton ('dandwiki')(Warlock)", true));
        pick.add(new Option("The God of Halloween ('dandwiki')(Warlock)", true));
        pick.add(new Option("The Godslayer ('dandwiki')(Warlock)", true));
        pick.add(new Option("The Great Storm ('dandwiki')(Warlock)", true));
        pick.add(new Option("The Great White Wyrm ('dandwiki')(Warlock)", true));
        pick.add(new Option("The Greatwyrm ('dandwiki')(Warlock)", true));
        pick.add(new Option("The Grey Errant ('dandwiki')(Warlock)", true));
        pick.add(new Option("The Hag ('dandwiki')(Warlock)", true));
        pick.add(new Option("The Haunting ('dandwiki')(Warlock)", true));
        pick.add(new Option("The Hexadin ('dandwiki')(Warlock)", true));
        pick.add(new Option("The Hijacked Magick ('dandwiki')(Warlock)", true));
        pick.add(new Option("The Hive Queen ('dandwiki')(Warlock)", true));
        pick.add(new Option("The Hivemind ('dandwiki')(Warlock)", true));
        pick.add(new Option("The Hollow ('dandwiki')(Warlock)", true));
        pick.add(new Option("The Hollow, Variant ('dandwiki')(Warlock)", true));
        pick.add(new Option("The Horned Man ('dandwiki')(Warlock)", true));
        pick.add(new Option("The Horrible Goose ('dandwiki')(Warlock)", true));
        pick.add(new Option("The Host ('dandwiki')(Warlock)", true));
        pick.add(new Option("The Hunt Lord ('dandwiki')(Warlock)", true));
        pick.add(new Option("The Imaginary Friend ('dandwiki')(Warlock)", true));
        pick.add(new Option("The Imagined One ('dandwiki')(Warlock)", true));
        pick.add(new Option("The Inescapable Void ('dandwiki')(Warlock)", true));
        pick.add(new Option("The Infestation ('dandwiki')(Warlock)", true));
        pick.add(new Option("The Keeper ('dandwiki')(Warlock)", true));
        pick.add(new Option("The Kingdom Hearts ('dandwiki')(Warlock)", true));
        pick.add(new Option("The Kingpin ('dandwiki')(Warlock)", true));
        pick.add(new Option("The Latex Quartet ('dandwiki')(Warlock)", true));
        pick.add(new Option("The Leper ('dandwiki')(Warlock)", true));
        pick.add(new Option("The Lie ('dandwiki')(Warlock)", true));
        pick.add(new Option("The Lightless Flame ('dandwiki')(Warlock)", true));
        pick.add(new Option("The Lucky Lady ('dandwiki')(Warlock)", true));
        pick.add(new Option("The Madgod Patron ('dandwiki')(Warlock)", true));
        pick.add(new Option("The Magical Girl ('dandwiki')(Warlock)", true));
        pick.add(new Option("The Magical Girl Pact, Variant ('dandwiki')(Warlock)", true));
        pick.add(new Option("The Mana ('dandwiki')(Warlock)", true));
        pick.add(new Option("The Midas Patron ('dandwiki')(Warlock)", true));
        pick.add(new Option("The Moebius ('dandwiki')(Warlock)", true));
        pick.add(new Option("The Monster Under The Bed ('dandwiki')(Warlock)", true));
        pick.add(new Option("The Moon ('dandwiki')(Warlock)", true));
        pick.add(new Option("The Mother of Puppets ('dandwiki')(Warlock)", true));
        pick.add(new Option("The Naga ('dandwiki')(Warlock)", true));
        pick.add(new Option("The Night Mistress ('dandwiki')(Warlock)", true));
        pick.add(new Option("The Nightmare ('dandwiki')(Warlock)", true));
        pick.add(new Option("The Nightmare, Variant ('dandwiki')(Warlock)", true));
        pick.add(new Option("The Old Gods ('dandwiki')(Warlock)", true));
        pick.add(new Option("The One Alone ('dandwiki')(Warlock)", true));
        pick.add(new Option("The Orb Bearer ('dandwiki')(Warlock)", true));
        pick.add(new Option("The Ouroboros ('dandwiki')(Warlock)", true));
        pick.add(new Option("The Outsider ('dandwiki')(Warlock)", true));
        pick.add(new Option("The Outsider, Variant ('dandwiki')(Warlock)", true));
        pick.add(new Option("The Parasite ('dandwiki')(Warlock)", true));
        pick.add(new Option("The Parasitic Host ('dandwiki')(Warlock)", true));
        pick.add(new Option("The Platinum Dragon ('dandwiki')(Warlock)", true));
        pick.add(new Option("The Pretender ('dandwiki')(Warlock)", true));
        pick.add(new Option("The Primal Lord ('dandwiki')(Warlock)", true));
        pick.add(new Option("The Puppeteer ('dandwiki')(Warlock)", true));
        pick.add(new Option("The Purgatorial Infusion ('dandwiki')(Warlock)", true));
        pick.add(new Option("The Queen of Spiders ('dandwiki')(Warlock)", true));
        pick.add(new Option("The Ring Lord ('dandwiki')(Warlock)", true));
        pick.add(new Option("The Risen War ('dandwiki')(Warlock)", true));
        pick.add(new Option("The Sentient Compendium ('dandwiki')(Warlock)", true));
        pick.add(new Option("The Seraphim ('dandwiki')(Warlock)", true));
        pick.add(new Option("The Shadow Dragon ('dandwiki')(Warlock)", true));
        pick.add(new Option("The Shadowmaster ('dandwiki')(Warlock)", true));
        pick.add(new Option("The Skull of Orcus ('dandwiki')(Warlock)", true));
        pick.add(new Option("The Sky Wrath Infusion ('dandwiki')(Warlock)", true));
        pick.add(new Option("The Slime ('dandwiki')(Warlock)", true));
        pick.add(new Option("The Soul of the World ('dandwiki')(Warlock)", true));
        pick.add(new Option("The Souleater ('dandwiki')(Warlock)", true));
        pick.add(new Option("The Soulstealer ('dandwiki')(Warlock)", true));
        pick.add(new Option("The Spirit Sharer ('dandwiki')(Warlock)", true));
        pick.add(new Option("The Star ('dandwiki')(Warlock)", true));
        pick.add(new Option("The Starry Night ('dandwiki')(Warlock)", true));
        pick.add(new Option("The Storm Lord ('dandwiki')(Warlock)", true));
        pick.add(new Option("The Sunken Sky ('dandwiki')(Warlock)", true));
        pick.add(new Option("The Sylvan Hermitree ('dandwiki')(Warlock)", true));
        pick.add(new Option("The Symbiote ('dandwiki')(Warlock)", true));
        pick.add(new Option("The System ('dandwiki')(Warlock)", true));
        pick.add(new Option("The Terminus Which Waits For All ('dandwiki')(Warlock)", true));
        pick.add(new Option("The Thief ('dandwiki')(Warlock)", true));
        pick.add(new Option("The Thousand-Lives ('dandwiki')(Warlock)", true));
        pick.add(new Option("The Throne of Heroes ('dandwiki')(Warlock)", true));
        pick.add(new Option("The Throne of Souls ('dandwiki')(Warlock)", true));
        pick.add(new Option("The Titan ('dandwiki')(Warlock)", true));
        pick.add(new Option("The Transistor ('dandwiki')(Warlock)", true));
        pick.add(new Option("The Traveler ('dandwiki')(Warlock)", true));
        pick.add(new Option("The Twisting Deceit ('dandwiki')(Warlock)", true));
        pick.add(new Option("The Typhoon ('dandwiki')(Warlock)", true));
        pick.add(new Option("The Uncanny Stranger ('dandwiki')(Warlock)", true));
        pick.add(new Option("The Unwilling Master ('dandwiki')(Warlock)", true));
        pick.add(new Option("The Vampire ('dandwiki')(Warlock)", true));
        pick.add(new Option("The Vessel of Souls ('dandwiki')(Warlock)", true));
        pick.add(new Option("The Visceral Flesh ('dandwiki')(Warlock)", true));
        pick.add(new Option("The Void ('dandwiki')(Warlock)", true));
        pick.add(new Option("The Void, 2nd Variant ('dandwiki')(Warlock)", true));
        pick.add(new Option("The Void, Variant ('dandwiki')(Warlock)", true));
        pick.add(new Option("The Wabash Cannonball ('dandwiki')(Warlock)", true));
        pick.add(new Option("The Warlord ('dandwiki')(Warlock)", true));
        pick.add(new Option("The Warlord, Original Variant ('dandwiki')(Warlock)", true));
        pick.add(new Option("The Warlord, Variant ('dandwiki')(Warlock)", true));
        pick.add(new Option("The Wheel ('dandwiki')(Warlock)", true));
        pick.add(new Option("The Windcrasher ('dandwiki')(Warlock)", true));
        pick.add(new Option("Time ('dandwiki')(Warlock)", true));
        pick.add(new Option("Valkyrie Patron ('dandwiki')(Warlock)", true));
        pick.add(new Option("Void Bringer ('dandwiki')(Warlock)", true));
        pick.add(new Option("Warden of Hearts ('dandwiki')(Warlock)", true));
        pick.add(new Option("Warlock Otherworldly Patron: Juiblex ('dandwiki')(Warlock)", true));
        Option a = Question.ask(pick, "Choose your Patron");
        list.add(a);
        pick = new ArrayList<Option>();
        pick.add(new Option("Pact of the Blade (Warlock)"));
        pick.add(new Option("Pact of the Chain (Warlock)"));
        pick.add(new Option("Pact of the Tome (Warlock)"));
        pick.add(new Option("Pact of the Talisman (Warlock)"));
        a = Question.ask(pick, "Choose your Pact Boon");
        list.add(a);

        return list;
    }
}

