package src.Choices;

import src.Choice;
import src.Option;
import src.Question;

import java.util.ArrayList;
import java.util.Arrays;

public class BGs extends Choice {
    public BGs(){
        super();
    }
    public ArrayList<Option> run(){
        ArrayList<Option> list = new ArrayList<Option>();
        ArrayList<Option> pick = new ArrayList<Option>();
        pick.add(new BackGround("Acolyte",
                new ArrayList<>(Arrays.asList(//Traits
                        new Option ("I idolize a particular hero of my faith, and constantly refer to that person's deeds and example."),
                        new Option ("I can find common ground between the fiercest enemies, empathizing with them and always working toward peace."),
                        new Option ("I see omens in every event and action. The gods try to speak to us, we just need to listen."),
                        new Option ("Nothing can shake my optimistic attitude."),
                        new Option ("I quote (or misquote) sacred texts and proverbs in almost every situation."),
                        new Option ("I am tolerant of other faiths and respect the worship of other gods."),
                        new Option ("I am intolerant of other faiths and condemn the worship of other gods."),
                        new Option ("I've enjoyed fine food, drink, and high society among my temple's elite. Rough living grates on me."),
                        new Option ("I've spent so long in the temple that I have little practical experience dealing with people in the outside world."),
                        new Option ("Other."))),
                new ArrayList<>(Arrays.asList(//Ideals
                        new Option ("Tradition. The ancient traditions of worship and sacrifice must be preserved and upheld. (Lawful)"),
                        new Option ("Charity. I always try to help those in need, no matter what the personal cost. (Good)"),
                        new Option ("Change. We must help bring about the changes the gods are constantly working in the world. (Chaotic)"),
                        new Option ("Power. I hope to one day rise to the top of my faith's religious hierarchy. (Lawful)"),
                        new Option ("Faith. I trust that my deity will guide my actions. I have faith that if I work hard, things will go well. (Lawful)"),
                        new Option ("Aspiration. I seek to prove myself worthy of my god's favor by matching my actions against their teachings. (Any)"),
                        new Option ("Other."))),
                new ArrayList<>(Arrays.asList(//Bonds
                        new Option ("I would die to recover an ancient relic of my faith that was lost long ago."),
                        new Option ("I will someday get revenge on the corrupt temple hierarchy who branded me a heretic."),
                        new Option ("I owe my life to the priest who took me in when my parents died."),
                        new Option ("Everything I do is for the common people."),
                        new Option ("I will do anything to protect the temple where I served."),
                        new Option ("I seek to preserve a sacred text that my enemies consider heretical and seek to destroy."),
                        new Option ("Other."))),
                new ArrayList<>(Arrays.asList(//Flaws
                        new Option ("I judge others harshly, and myself even more severely."),
                        new Option ("I put too much trust in those who wield power within my temple's hierarchy."),
                        new Option ("My piety sometimes leads me to blindly trust those that profess faith in my god."),
                        new Option ("I am inflexible in my thinking."),
                        new Option ("I am suspicious of strangers and expect the worst of them."),
                        new Option ("Once I pick a goal, I become obsessed with it to the detriment of everything else in my life."),
                        new Option ("Other.")))));
        pick.add(new BackGround("Anthropologist",
                new ArrayList<>(Arrays.asList(//Traits
                        new Option ("I prefer the company of those who aren't like me, including people of other races."),
                        new Option ("I'm a stickler when it comes to observing proper etiquette and local customs."),
                        new Option ("I would rather observe than meddle."),
                        new Option ("By living among violent people, I have become desensitized to violence."),
                        new Option ("I would risk life and limb to discover a new culture or unravel the secrets of a dead one."),
                        new Option ("When I arrive at a new settlement for the first time, I must learn all its customs."),
                        new Option ("Other."))),
                new ArrayList<>(Arrays.asList(//Ideals
                        new Option ("Discovery. I want to be the first person to discover a lost culture. (Any)"),
                        new Option ("Distance. One must not interfere with the affairs of another culture – even one in need of aid. (Lawful)"),
                        new Option ("Knowledge. By understanding other races and cultures, we learn to understand ourselves. (Any)"),
                        new Option ("Power. Common people crave strong leadership, and I do my utmost to provide it. (Lawful)"),
                        new Option ("Protection. I must do everything possible to save a society facing extinction. (Good)"),
                        new Option ("Indifferent. Life is cruel. What's the point in saving people if they're going to die anyway? (Chaotic)"),
                        new Option ("Other."))),
                new ArrayList<>(Arrays.asList(//Bonds
                        new Option ("My mentor gave me a journal filled with lore and wisdom. Losing it would devastate me."),
                        new Option ("Having lived among the people of a primeval tribe or clan, I long to return and see how they are faring."),
                        new Option ("Years ago, tragedy struck the members of an isolated society I befriended, and I will honor them."),
                        new Option ("I want to learn more about a particular humanoid culture that fascinates me."),
                        new Option ("I seek to avenge a clan, tribe, kingdom, or empire that was wiped out."),
                        new Option ("I have a trinket that I believe is the key to finding a long-lost society."),
                        new Option ("Other."))),
                new ArrayList<>(Arrays.asList(//Flaws
                        new Option ("Boats make me seasick."),
                        new Option ("I talk to myself, and I don't make friends easily."),
                        new Option ("I believe that I'm intellectually superior to people from other cultures and have much to teach them."),
                        new Option ("I've picked up some unpleasant habits living among races such as goblins, lizardfolk, or orcs."),
                        new Option ("I complain about everything."),
                        new Option ("I wear a tribal mask and never take it off."),
                        new Option ("Other.")))));
        pick.add(new BackGround("Archaeologist",
                new ArrayList<>(Arrays.asList(//Traits
                        new Option ("I love a good puzzle or mystery."),
                        new Option ("I'm a pack rat who never throws anything away."),
                        new Option ("Fame is more important to me than money."),
                        new Option ("I have no qualms about stealing from the dead."),
                        new Option ("I'm happier in a dusty old tomb than I am in the centers of civilization."),
                        new Option ("Traps don't make me nervous. Idiots who trigger traps make me nervous."),
                        new Option ("I might fail, but I will never give up."),
                        new Option ("You might think I'm a scholar, but I love a good brawl. These fists were made for punching."),
                        new Option ("Other."))),
                new ArrayList<>(Arrays.asList(//Ideals
                        new Option ("Preservation. That artifact belongs in a museum. (Good)"),
                        new Option ("Greed. I won't risk my life for nothing. I expect some kind of payment. (Any)"),
                        new Option ("Death Wish. Nothing is more exhilarating than a narrow escape from the jaws of death. (Chaotic)"),
                        new Option ("Dignity. The dead and their belongings deserve to be treated with respect. (Lawful)"),
                        new Option ("Immortality. All my exploring is part of a plan to find the secret of everlasting life. (Any)"),
                        new Option ("Danger. With every great discovery comes grave danger. The two walk hand in hand. (Any)"),
                        new Option ("Other."))),
                new ArrayList<>(Arrays.asList(//Bonds
                        new Option ("Ever since I was a child, I've heard stories about a lost city. I aim to find it, learn its secrets, and earn my place in the history books."),
                        new Option ("I want to find my mentor, who disappeared on an expedition some time ago."),
                        new Option ("I have a friendly rival. Only one of us can be the best, and I aim to prove it's me."),
                        new Option ("I won't sell an art object or other treasure that has historical significance or is one of a kind."),
                        new Option ("I'm secretly in love with the wealthy patron who sponsors my archaeological exploits."),
                        new Option ("I hope to bring prestige to a library, a museum, or a university."),
                        new Option ("Other."))),
                new ArrayList<>(Arrays.asList(//Flaws
                        new Option ("I have a secret fear of some common wild animal – and in my work, I see them everywhere."),
                        new Option ("I can't leave a room without searching it for secret doors."),
                        new Option ("When I'm not exploring dungeons or ruins, I get jittery and impatient."),
                        new Option ("I have no time for friends or family. I spend every waking moment thinking about and preparing for my next expedition."),
                        new Option ("When given the choice of going left or right, I always go left."),
                        new Option ("When given the choice of going left or right, I always go right."),
                        new Option ("I can't sleep except in total darkness."),
                        new Option ("Other."))),
                new ArrayList<ArrayList<Option>>(Arrays.asList(new ArrayList<Option>(Arrays.asList(
                        new Option ("10 ft Pole (Signature Item)"),
                        new Option ("Medallion (Signature Item)"),
                        new Option ("Crowbar (Signature Item)"),
                        new Option ("Shovel (Signature Item)"),
                        new Option ("Hat (Signature Item)"),
                        new Option ("Sledgehammer (Signature Item)"),
                        new Option ("Hooded Lantern (Signature Item)"),
                        new Option ("Whip (Signature Item)")))))));
        pick.add(new BackGround("Athlete",
                new ArrayList<>(Arrays.asList(//Traits
                        new Option ("I feel most at peace during physical exertion, whether exercise or battle."),
                        new Option ("I don't like to sit idle."),
                        new Option ("I have a daily exercise routine I refuse to break."),
                        new Option ("Obstacles exist to be overcome."),
                        new Option ("When I see others struggling, I offer to help."),
                        new Option ("I love to trade banter and gibes."),
                        new Option ("Anything worth doing is worth doing best."),
                        new Option ("I get irritated if people praise someone else and not me."),
                        new Option ("Other."))),
                new ArrayList<>(Arrays.asList(//Ideals
                        new Option ("Competition. I strive to test myself in all things. (Chaotic)"),
                        new Option ("Triumph. The best part of winning is seeing my rivals brought low. (Evil)"),
                        new Option ("Camaraderie. The strongest bonds are forged through struggle. (Good)"),
                        new Option ("People. I strive to inspire my spectators. (Neutral)"),
                        new Option ("Tradition. Every game has rules, and the playing field must be level. (Lawful)"),
                        new Option ("Growth. Lessons hide in victory and defeat. (Any)"),
                        new Option ("Other."))),
                new ArrayList<>(Arrays.asList(//Bonds
                        new Option ("My teammates are my family."),
                        new Option ("I will overcome a rival and prove myself their better."),
                        new Option ("My mistake got someone hurt. Ill never make that mistake again."),
                        new Option ("I will be the best for the honor and glory of my home."),
                        new Option ("The person who trained me is the most important person in my world."),
                        new Option ("I strive to live up to a specific hero's example."),
                        new Option ("Other."))),
                new ArrayList<>(Arrays.asList(//Flaws
                        new Option ("I indulge in a habit that threatens my reputation or health."),
                        new Option ("I'll do absolutely anything to win."),
                        new Option ("I ignore anyone who doesn't compete and anyone who loses to me."),
                        new Option ("I have lingering pain of old injuries."),
                        new Option ("Any defeat or failure on my part is because my opponents cheated."),
                        new Option ("I must be the captain of any group I join."),
                        new Option ("Other."))),
                new ArrayList<ArrayList<Option>>(Arrays.asList(new ArrayList<Option>(Arrays.asList(
                        new Option ("Marathon (Favored Event)"),
                        new Option ("Long-Distance Running (Favored Event)"),
                        new Option ("Wrestling (Favored Event)"),
                        new Option ("Boxing (Favored Event)"),
                        new Option ("Chariot or Horse Race (Favored Event)"),
                        new Option ("Pankration (mixed unarmed combat) (Favored Event)"),
                        new Option ("Hoplite Race (racing in full armor with a unit) (Favored Event)"),
                        new Option ("Pentathlon (running, long jump, discus, javelin, wrestling) (Favored Event)")))))));
        pick.add(new BackGround("Charlatan",
                new ArrayList<>(Arrays.asList(//Traits
                        new Option ("I fall in and out of love easily, and am always pursuing someone."),
                        new Option ("I have a joke for every occasion, especially occasions where humor is inappropriate."),
                        new Option ("Flattery is my preferred trick for getting what I want"),
                        new Option ("I'm a born gambler who can't resist taking a risk for a potential payoff."),
                        new Option ("I lie about almost everything, even when there's no good reason to."),
                        new Option ("Sarcasm and insults are my weapons of choice."),
                        new Option ("I keep multiple holy symbols on me and invoke whatever deity might come in useful at any given moment."),
                        new Option ("I pocket anything I see that might have some value.\n"),
                        new Option ("Other."))),
                new ArrayList<>(Arrays.asList(//Ideals
                        new Option ("Independence. I am a free spirit – no one tells me what to do. (Chaotic)"),
                        new Option ("Fairness. I never target people who can't afford to lose a few coins. (Lawful)"),
                        new Option ("Charity. I distribute the money I acquire to the people who really need it. (Good)"),
                        new Option ("Creativity. I never run the same con twice. (Chaotic)"),
                        new Option ("Friendship. Material goods come and go. Bonds of friendship last forever. (Good)"),
                        new Option ("Aspiration. I'm determined to make something of myself. (Any)"),
                        new Option ("Other."))),
                new ArrayList<>(Arrays.asList(//Bonds
                        new Option ("I fleeced the wrong person and must work to ensure that this individual never crosses paths with me or those I care about."),
                        new Option ("I owe everything to my mentor – a horrible person who's probably rotting in jail somewhere."),
                        new Option ("Somewhere out there, I have a child who doesn't know me. I'm making the world better for him or her."),
                        new Option ("I come from a noble family, and one day I'll reclaim my lands and title from those who stole them from me."),
                        new Option ("A powerful person killed someone I love. Some day soon, I'll have my revenge."),
                        new Option ("I swindled and ruined a person who didn't deserve it. I seek to atone for my misdeeds but might never be able to forgive myself."),
                        new Option ("Other."))),
                new ArrayList<>(Arrays.asList(//Flaws
                        new Option ("I can't resist a pretty face."),
                        new Option ("I'm always in debt. I spend my ill-gotten gains on decadent luxuries faster than I bring them in."),
                        new Option ("I'm convinced that no one could ever fool me the way I fool others."),
                        new Option ("I'm too greedy for my own good. I can't resist taking a risk if there's money involved."),
                        new Option ("I can't resist swindling people who are more powerful than me."),
                        new Option ("I hate to admit it and will hate myself for it, but I'll run and preserve my own hide if the going gets tough."),
                        new Option ("Other."))),
                new ArrayList<ArrayList<Option>>(Arrays.asList(new ArrayList<Option>(Arrays.asList(
                        new Option ("I cheat at games of chance. (Favored Scheme)"),
                        new Option ("I shave coins or forge documents. (Favored Scheme)"),
                        new Option ("I insinuate myself into people's lives to prey on their weakness and secure their fortunes. (Favored Scheme)"),
                        new Option ("I put on new identities like clothes. (Favored Scheme)"),
                        new Option ("I run sleight-of-hand cons on street corners. (Favored Scheme)"),
                        new Option ("I convince people that worthless junk is worth their hard-earned money. (Favored Scheme)")))))));
        pick.add(new BackGround("City Watch",//Replace with soldier trait, ideals, bonds, flaws
                new ArrayList<>(Arrays.asList(//Traits
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option ("Other."))),
                new ArrayList<>(Arrays.asList(//Ideals
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option ("Other."))),
                new ArrayList<>(Arrays.asList(//Bonds
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option ("Other."))),
                new ArrayList<>(Arrays.asList(//Flaws
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option ("Other.")))));
        pick.add(new BackGround("Clan Crafter", // Replace with Guild Artisan
                new ArrayList<>(Arrays.asList(//Traits
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option ("Other."))),
                new ArrayList<>(Arrays.asList(//Ideals
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option ("Other."))),
                new ArrayList<>(Arrays.asList(//Bonds
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option ("Other."))),
                new ArrayList<>(Arrays.asList(//Flaws
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option ("Other.")))));
        pick.add(new BackGround("Cloistered Scholar", //sage
                new ArrayList<>(Arrays.asList(//Traits
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option ("Other."))),
                new ArrayList<>(Arrays.asList(//Ideals
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option ("Other."))),
                new ArrayList<>(Arrays.asList(//Bonds
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option ("Other."))),
                new ArrayList<>(Arrays.asList(//Flaws
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option ("Other.")))));
        pick.add(new BackGround("Courtier", //Guild Artisan
                new ArrayList<>(Arrays.asList(//Traits
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option ("Other."))),
                new ArrayList<>(Arrays.asList(//Ideals
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option ("Other."))),
                new ArrayList<>(Arrays.asList(//Bonds
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option ("Other."))),
                new ArrayList<>(Arrays.asList(//Flaws
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option ("Other.")))));
        pick.add(new BackGround("Criminal",
                new ArrayList<>(Arrays.asList(//Traits
                        new Option ("I always have a plan for what to do when things go wrong."),
                        new Option ("I am always calm, no matter what the situation. I never raise my voice or let my emotions control me."),
                        new Option ("The first thing I do in a new place is note the locations of everything valuable – or where such things could be hidden."),
                        new Option ("I would rather make a new friend than a new enemy."),
                        new Option ("I am incredibly slow to trust. Those who seem the fairest often have the most to hide."),
                        new Option ("I don't pay attention to the risks in a situation. Never tell me the odds."),
                        new Option ("The best way to get me to do something is to tell me I can't do it."),
                        new Option ("I blow up at the slightest insult."),
                        new Option ("Other."))),
                new ArrayList<>(Arrays.asList(//Ideals
                        new Option ("Honor. I don't steal from others in the trade. (Lawful)"),
                        new Option ("Freedom. Chains are meant to be broken, as are those who would forge them. (Chaotic)"),
                        new Option ("Charity. I steal from the wealthy so that I can help people in need. (Good)"),
                        new Option ("Greed. I will do whatever it takes to become wealthy. (Evil)"),
                        new Option ("People. I'm loyal to my friends, not to any ideals, and everyone else can take a trip down the Styx for all I care. (Neutral)"),
                        new Option ("Redemption. There's a spark of good in everyone. (Good)"),
                        new Option ("Other."))),
                new ArrayList<>(Arrays.asList(//Bonds
                        new Option ("I'm trying to pay off an old debt I owe to a generous benefactor."),
                        new Option ("My ill-gotten gains go to support my family."),
                        new Option ("Something important was taken from me, and I aim to steal it back."),
                        new Option ("I will become the greatest thief that ever lived."),
                        new Option ("I'm guilty of a terrible crime. I hope I can redeem myself for it."),
                        new Option ("Someone I loved died because of I mistake I made. That will never happen again."),
                        new Option ("Other."))),
                new ArrayList<>(Arrays.asList(//Flaws
                        new Option ("When I see something valuable, I can't think about anything but how to steal it."),
                        new Option ("When faced with a choice between money and my friends, I usually choose the money."),
                        new Option ("If there's a plan, I'll forget it. If I don't forget it, I'll ignore it."),
                        new Option ("I have a \"tell\" that reveals when I'm lying."),
                        new Option ("I turn tail and run when things look bad."),
                        new Option ("An innocent person is in prison for a crime that I committed. I'm okay with that."),
                        new Option ("Other."))),
                new ArrayList<ArrayList<Option>>(Arrays.asList(new ArrayList<Option>(Arrays.asList(
                        new Option ("Blackmailer (Criminal Specialty)"),
                        new Option ("Burglar (Criminal Specialty)"),
                        new Option ("Enforcer (Criminal Specialty)"),
                        new Option ("Fence (Criminal Specialty)"),
                        new Option ("Highway robber (Criminal Specialty)"),
                        new Option ("Hired Killer (Criminal Specialty)"),
                        new Option ("Pickpocket (Criminal Specialty)"),
                        new Option ("Smuggler (Criminal Specialty)"))),
                        new ArrayList<Option>(Arrays.asList(
                                new Option ("Criminal"),
                                new Option ("Spy (Criminal")))
                        ))));
        pick.add(new BackGround("Entertainer",
                new ArrayList<>(Arrays.asList(//Traits
                        new Option ("I know a story relevant to almost every situation."),
                        new Option ("Whenever I come to a new place, I collect local rumors and spread gossip."),
                        new Option ("I'm a hopeless romantic, always searching for that \"special someone.\""),
                        new Option ("Nobody stays angry at me or around me for long, since I can defuse any amount of tension."),
                        new Option ("I love a good insult, even one directed at me."),
                        new Option ("I get bitter if I'm not the center of attention."),
                        new Option ("I'll settle for nothing less than perfection."),
                        new Option ("I change my mood or my mind as quickly as I change key in a song."),
                        new Option ("Other."))),
                new ArrayList<>(Arrays.asList(//Ideals
                        new Option ("Beauty. When I perform, I make the world better than it was. (Good)"),
                        new Option ("Tradition. The stories, legends, and songs of the past must never be forgotten, for they teach us who we are. (Lawful)"),
                        new Option ("Creativity. The world is in need of new ideas and bold action. (Chaotic)"),
                        new Option ("Greed. I'm only in it for the money and fame. (Evil)"),
                        new Option ("People. I like seeing the smiles on people's faces when I perform. That's all that matters. (Neutral)"),
                        new Option ("Honesty. Art should reflect the soul; it should come from within and reveal who we really are. (Any)"),
                        new Option ("Other."))),
                new ArrayList<>(Arrays.asList(//Bonds
                        new Option ("My instrument is my most treasured possession, and it reminds me of someone I love."),
                        new Option ("Someone stole my precious instrument, and someday I'll get it back."),
                        new Option ("I want to be famous, whatever it takes."),
                        new Option ("I idolize a hero of the old tales and measure my deeds against that person's."),
                        new Option ("I will do anything to prove myself superior to my hated rival."),
                        new Option ("I would do anything for the other members of my old troupe."),
                        new Option ("Other."))),
                new ArrayList<>(Arrays.asList(//Flaws
                        new Option ("I'll do anything to win fame and renown."),
                        new Option ("I'm a sucker for a pretty face."),
                        new Option ("A scandal prevents me from ever going home again. That kind of trouble seems to follow me around."),
                        new Option ("I once satirized a noble who still wants my head. It was a mistake that I will likely repeat."),
                        new Option ("I have trouble keeping my true feelings hidden. My sharp tongue lands me in trouble."),
                        new Option ("Despite my best efforts, I am unreliable to my friends."),
                        new Option ("Other."))),
                new ArrayList<ArrayList<Option>>(Arrays.asList(new ArrayList<Option>(Arrays.asList(
                        new Option ("Actor (Routines)"),
                        new Option ("Dancer (Routines)"),
                        new Option ("Fire-eater (Routines)"),
                        new Option ("Jester (Routines)"),
                        new Option ("Juggler (Routines)"),
                        new Option ("Instrumentalist (Routines)"),
                        new Option ("Poet (Routines)"),
                        new Option ("Singer (Routines)"),
                        new Option ("Storyteller (Routines)"),
                        new Option ("Tumbler (Routines)")))))));
        pick.add(new BackGround("Faceless",
                new ArrayList<>(Arrays.asList(//Traits
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option ("Other."))),
                new ArrayList<>(Arrays.asList(//Ideals
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option ("Other."))),
                new ArrayList<>(Arrays.asList(//Bonds
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option ("Other."))),
                new ArrayList<>(Arrays.asList(//Flaws
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option ("Other.")))));
        pick.add(new BackGround("Faction Agent",
                new ArrayList<>(Arrays.asList(//Traits
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option ("Other."))),
                new ArrayList<>(Arrays.asList(//Ideals
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option ("Other."))),
                new ArrayList<>(Arrays.asList(//Bonds
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option ("Other."))),
                new ArrayList<>(Arrays.asList(//Flaws
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option ("Other.")))));
        pick.add(new BackGround("Far Traveler",
                new ArrayList<>(Arrays.asList(//Traits
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option ("Other."))),
                new ArrayList<>(Arrays.asList(//Ideals
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option ("Other."))),
                new ArrayList<>(Arrays.asList(//Bonds
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option ("Other."))),
                new ArrayList<>(Arrays.asList(//Flaws
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option ("Other.")))));
        pick.add(new BackGround("Fisher",
                new ArrayList<>(Arrays.asList(//Traits
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option ("Other."))),
                new ArrayList<>(Arrays.asList(//Ideals
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option ("Other."))),
                new ArrayList<>(Arrays.asList(//Bonds
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option ("Other."))),
                new ArrayList<>(Arrays.asList(//Flaws
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option ("Other.")))));
        pick.add(new BackGround("Folk Hero",
                new ArrayList<>(Arrays.asList(//Traits
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option ("Other."))),
                new ArrayList<>(Arrays.asList(//Ideals
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option ("Other."))),
                new ArrayList<>(Arrays.asList(//Bonds
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option ("Other."))),
                new ArrayList<>(Arrays.asList(//Flaws
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option ("Other.")))));
        pick.add(new BackGround("Giant Foundling",
                new ArrayList<>(Arrays.asList(//Traits
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option ("Other."))),
                new ArrayList<>(Arrays.asList(//Ideals
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option ("Other."))),
                new ArrayList<>(Arrays.asList(//Bonds
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option ("Other."))),
                new ArrayList<>(Arrays.asList(//Flaws
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option ("Other.")))));
        pick.add(new BackGround("Gladiator",
                new ArrayList<>(Arrays.asList(//Traits
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option ("Other."))),
                new ArrayList<>(Arrays.asList(//Ideals
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option ("Other."))),
                new ArrayList<>(Arrays.asList(//Bonds
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option ("Other."))),
                new ArrayList<>(Arrays.asList(//Flaws
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option ("Other.")))));
        pick.add(new BackGround("Guild Artisan",
                new ArrayList<>(Arrays.asList(//Traits
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option ("Other."))),
                new ArrayList<>(Arrays.asList(//Ideals
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option ("Other."))),
                new ArrayList<>(Arrays.asList(//Bonds
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option ("Other."))),
                new ArrayList<>(Arrays.asList(//Flaws
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option ("Other.")))));
        pick.add(new BackGround("Guild Merchant",
                new ArrayList<>(Arrays.asList(//Traits
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option ("Other."))),
                new ArrayList<>(Arrays.asList(//Ideals
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option ("Other."))),
                new ArrayList<>(Arrays.asList(//Bonds
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option ("Other."))),
                new ArrayList<>(Arrays.asList(//Flaws
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option ("Other.")))));
        pick.add(new BackGround("Haunted One",
                new ArrayList<>(Arrays.asList(//Traits
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option ("Other."))),
                new ArrayList<>(Arrays.asList(//Ideals
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option ("Other."))),
                new ArrayList<>(Arrays.asList(//Bonds
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option ("Other."))),
                new ArrayList<>(Arrays.asList(//Flaws
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option ("Other.")))));
        pick.add(new BackGround("Hermit",
                new ArrayList<>(Arrays.asList(//Traits
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option ("Other."))),
                new ArrayList<>(Arrays.asList(//Ideals
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option ("Other."))),
                new ArrayList<>(Arrays.asList(//Bonds
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option ("Other."))),
                new ArrayList<>(Arrays.asList(//Flaws
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option ("Other.")))));
        pick.add(new BackGround("House Agent",
                new ArrayList<>(Arrays.asList(//Traits
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option ("Other."))),
                new ArrayList<>(Arrays.asList(//Ideals
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option ("Other."))),
                new ArrayList<>(Arrays.asList(//Bonds
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option ("Other."))),
                new ArrayList<>(Arrays.asList(//Flaws
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option ("Other.")))));
        pick.add(new BackGround("Inheritor",
                new ArrayList<>(Arrays.asList(//Traits
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option ("Other."))),
                new ArrayList<>(Arrays.asList(//Ideals
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option ("Other."))),
                new ArrayList<>(Arrays.asList(//Bonds
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option ("Other."))),
                new ArrayList<>(Arrays.asList(//Flaws
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option ("Other.")))));
        pick.add(new BackGround("Investigator (VRGR)",
                new ArrayList<>(Arrays.asList(//Traits
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option ("Other."))),
                new ArrayList<>(Arrays.asList(//Ideals
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option ("Other."))),
                new ArrayList<>(Arrays.asList(//Bonds
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option ("Other."))),
                new ArrayList<>(Arrays.asList(//Flaws
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option ("Other.")))));
        pick.add(new BackGround("Knight of the Order",
                new ArrayList<>(Arrays.asList(//Traits
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option ("Other."))),
                new ArrayList<>(Arrays.asList(//Ideals
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option ("Other."))),
                new ArrayList<>(Arrays.asList(//Bonds
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option ("Other."))),
                new ArrayList<>(Arrays.asList(//Flaws
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option ("Other.")))));
        pick.add(new BackGround("Marine",
                new ArrayList<>(Arrays.asList(//Traits
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option ("Other."))),
                new ArrayList<>(Arrays.asList(//Ideals
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option ("Other."))),
                new ArrayList<>(Arrays.asList(//Bonds
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option ("Other."))),
                new ArrayList<>(Arrays.asList(//Flaws
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option ("Other.")))));
        pick.add(new BackGround("Mercenary Veteran",
                new ArrayList<>(Arrays.asList(//Traits
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option ("Other."))),
                new ArrayList<>(Arrays.asList(//Ideals
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option ("Other."))),
                new ArrayList<>(Arrays.asList(//Bonds
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option ("Other."))),
                new ArrayList<>(Arrays.asList(//Flaws
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option ("Other.")))));
        pick.add(new BackGround("Noble",
                new ArrayList<>(Arrays.asList(//Traits
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option ("Other."))),
                new ArrayList<>(Arrays.asList(//Ideals
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option ("Other."))),
                new ArrayList<>(Arrays.asList(//Bonds
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option ("Other."))),
                new ArrayList<>(Arrays.asList(//Flaws
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option ("Other.")))));
        pick.add(new BackGround("Outlander",
                new ArrayList<>(Arrays.asList(//Traits
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option ("Other."))),
                new ArrayList<>(Arrays.asList(//Ideals
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option ("Other."))),
                new ArrayList<>(Arrays.asList(//Bonds
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option ("Other."))),
                new ArrayList<>(Arrays.asList(//Flaws
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option ("Other.")))));
        pick.add(new BackGround("Pirate",
                new ArrayList<>(Arrays.asList(//Traits
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option ("Other."))),
                new ArrayList<>(Arrays.asList(//Ideals
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option ("Other."))),
                new ArrayList<>(Arrays.asList(//Bonds
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option ("Other."))),
                new ArrayList<>(Arrays.asList(//Flaws
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option ("Other.")))));
        pick.add(new BackGround("Rewarded",
                new ArrayList<>(Arrays.asList(//Traits
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option ("Other."))),
                new ArrayList<>(Arrays.asList(//Ideals
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option ("Other."))),
                new ArrayList<>(Arrays.asList(//Bonds
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option ("Other."))),
                new ArrayList<>(Arrays.asList(//Flaws
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option ("Other.")))));
        pick.add(new BackGround("Ruined",
                new ArrayList<>(Arrays.asList(//Traits
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option ("Other."))),
                new ArrayList<>(Arrays.asList(//Ideals
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option ("Other."))),
                new ArrayList<>(Arrays.asList(//Bonds
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option ("Other."))),
                new ArrayList<>(Arrays.asList(//Flaws
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option ("Other.")))));
        pick.add(new BackGround("Rune Carver",
                new ArrayList<>(Arrays.asList(//Traits
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option ("Other."))),
                new ArrayList<>(Arrays.asList(//Ideals
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option ("Other."))),
                new ArrayList<>(Arrays.asList(//Bonds
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option ("Other."))),
                new ArrayList<>(Arrays.asList(//Flaws
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option ("Other.")))));
        pick.add(new BackGround("Sage",
                new ArrayList<>(Arrays.asList(//Traits
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option ("Other."))),
                new ArrayList<>(Arrays.asList(//Ideals
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option ("Other."))),
                new ArrayList<>(Arrays.asList(//Bonds
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option ("Other."))),
                new ArrayList<>(Arrays.asList(//Flaws
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option ("Other.")))));
        pick.add(new BackGround("Sailor",
                new ArrayList<>(Arrays.asList(//Traits
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option ("Other."))),
                new ArrayList<>(Arrays.asList(//Ideals
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option ("Other."))),
                new ArrayList<>(Arrays.asList(//Bonds
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option ("Other."))),
                new ArrayList<>(Arrays.asList(//Flaws
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option ("Other.")))));
        pick.add(new BackGround("Shipwright",
                new ArrayList<>(Arrays.asList(//Traits
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option ("Other."))),
                new ArrayList<>(Arrays.asList(//Ideals
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option ("Other."))),
                new ArrayList<>(Arrays.asList(//Bonds
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option ("Other."))),
                new ArrayList<>(Arrays.asList(//Flaws
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option ("Other.")))));
        pick.add(new BackGround("Smuggler",
                new ArrayList<>(Arrays.asList(//Traits
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option ("Other."))),
                new ArrayList<>(Arrays.asList(//Ideals
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option ("Other."))),
                new ArrayList<>(Arrays.asList(//Bonds
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option ("Other."))),
                new ArrayList<>(Arrays.asList(//Flaws
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option ("Other.")))));
        pick.add(new BackGround("Soldier",
                new ArrayList<>(Arrays.asList(//Traits
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option ("Other."))),
                new ArrayList<>(Arrays.asList(//Ideals
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option ("Other."))),
                new ArrayList<>(Arrays.asList(//Bonds
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option ("Other."))),
                new ArrayList<>(Arrays.asList(//Flaws
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option ("Other.")))));
        pick.add(new BackGround("Spy",
                new ArrayList<>(Arrays.asList(//Traits
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option ("Other."))),
                new ArrayList<>(Arrays.asList(//Ideals
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option ("Other."))),
                new ArrayList<>(Arrays.asList(//Bonds
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option ("Other."))),
                new ArrayList<>(Arrays.asList(//Flaws
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option ("Other.")))));
        pick.add(new BackGround("Urban Bounty Hunter",
                new ArrayList<>(Arrays.asList(//Traits
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option ("Other."))),
                new ArrayList<>(Arrays.asList(//Ideals
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option ("Other."))),
                new ArrayList<>(Arrays.asList(//Bonds
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option ("Other."))),
                new ArrayList<>(Arrays.asList(//Flaws
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option ("Other.")))));
        pick.add(new BackGround("Urchin",
                new ArrayList<>(Arrays.asList(//Traits
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option ("Other."))),
                new ArrayList<>(Arrays.asList(//Ideals
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option ("Other."))),
                new ArrayList<>(Arrays.asList(//Bonds
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option ("Other."))),
                new ArrayList<>(Arrays.asList(//Flaws
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option (""),
                        new Option ("Other.")))));

        Option a = Question.ask(pick, "Choose your background");
        list.add(a);

        return list;
    }
}